import re
import time

lipsum = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum enim nisi, bibendum finibus sem eget, dignissim aliquet ipsum. Aenean aliquet placerat pretium. Nunc cursus auctor rhoncus. Sed a ex eget orci sodales convallis ac et purus. Morbi sem sapien, scelerisque ac massa eu, viverra lacinia nulla. Pellentesque malesuada blandit est, vel scelerisque felis fringilla eget. Sed ut lectus et nisi suscipit faucibus sed id felis. Praesent metus erat, dictum eget pulvinar non, mattis id nibh. Nam ac nulla in libero molestie cursus eleifend sagittis odio. Donec blandit massa in lectus tristique, in egestas lorem cursus. Curabitur tincidunt purus nec nulla semper, vel placerat ex consequat. Sed erat tortor, condimentum et ipsum ac, tincidunt rutrum est. Donec mattis vehicula eros sed posuere. Fusce consectetur, magna ut faucibus mattis, nunc risus facilisis mi, eu ornare tellus eros id lacus. Donec pulvinar leo lectus, sit amet placerat sem congue ut. Nam vitae tincidunt quam.

Quisque condimentum eros et bibendum pellentesque. Donec auctor sem quis arcu varius eleifend. Praesent in luctus nibh, at vestibulum massa. Curabitur mauris augue, malesuada eu hendrerit id, ornare ut ante. Nam mattis felis et lacus euismod, at faucibus lacus porttitor. Duis nec leo ex. Maecenas at lorem nunc.

Ut aliquet facilisis efficitur. Integer id tortor vestibulum, porttitor ex vitae, semper nisl. Nunc tincidunt lacus iaculis lacus volutpat, at dapibus quam fermentum. Donec fermentum sem pretium ex dignissim placerat. Donec euismod hendrerit cursus. Sed pellentesque quis massa vitae ultrices. Suspendisse ullamcorper gravida augue quis dictum. Cras aliquam massa eu euismod rhoncus. Aliquam nec egestas purus, eget commodo tellus.

Sed sem dui, fermentum in rhoncus quis, feugiat id leo. Mauris eleifend augue quis vestibulum vulputate. Aliquam a tempus nisi. Sed convallis, felis id volutpat condimentum, ex ex tempus risus, auctor interdum metus diam vitae turpis. Donec sed sapien non sem congue condimentum vulputate vel purus. Sed eget sodales dui, quis vehicula nisi. Etiam eu posuere odio, a varius orci. Nullam sodales orci sed odio luctus porttitor. Nam tellus sem, tincidunt ac dolor nec, tempus finibus enim.

Sed fringilla ipsum leo, nec commodo lorem viverra vel. Nam faucibus eros et orci convallis aliquam. Phasellus mauris nisl, rhoncus ac magna a, rhoncus egestas neque. Donec nulla purus, tempus sed massa quis, blandit scelerisque lectus. Ut vestibulum, urna eget posuere elementum, nisi mi tristique urna, eget gravida purus magna id nulla. Etiam sed risus sagittis, vulputate arcu at, mollis orci. Phasellus auctor felis est, placerat commodo sem consequat id. Morbi tempus laoreet condimentum.

Morbi tristique blandit feugiat. Aenean nulla magna, ornare in mi a, auctor pulvinar mi. Pellentesque eget suscipit diam. Aliquam in consequat eros, a fermentum ligula. Suspendisse nec nibh vulputate, faucibus ante ut, dictum odio. Nunc placerat id augue id posuere. Nunc dolor orci, vulputate vel sapien ac, semper commodo tellus. In fermentum dignissim orci.

Vestibulum hendrerit lorem sit amet sem interdum, quis aliquet lectus dapibus. Praesent ultricies velit eu tellus hendrerit mattis. Mauris tempor pretium tellus. Nunc ultricies ultricies pellentesque. Praesent volutpat ligula in dictum blandit. Nulla maximus et risus elementum dignissim. Aliquam vehicula faucibus facilisis. Aliquam erat volutpat. Suspendisse quis mauris lectus. Mauris tellus diam, hendrerit sed massa vitae, finibus malesuada orci. Curabitur eu finibus nisl, a mattis dolor. Morbi nec quam sapien. Pellentesque sed tempor orci.

Quisque sit amet elit id magna vehicula faucibus sit amet vitae purus. Sed ac commodo magna, sed rhoncus odio. Vivamus molestie aliquam odio, ac bibendum odio pulvinar eu. Sed et neque sagittis, rhoncus mi ac, pellentesque ex. Etiam eget odio augue. Nulla sollicitudin dictum eros, sit amet bibendum nisl tincidunt vel. Sed eu ornare ante. Maecenas id felis id ante hendrerit maximus ut sagittis erat.

Integer non diam sed est scelerisque rutrum. Quisque est purus, lobortis et ligula ac, commodo blandit urna. Maecenas id libero at justo pulvinar tincidunt a sed odio. Phasellus ornare ex eu consectetur malesuada. Fusce tortor dui, tempus ut imperdiet vel, posuere a lorem. Ut eget lectus ante. Curabitur metus eros, vehicula vitae posuere ut, interdum vitae magna. Etiam porta eget tortor a tincidunt. Cras et facilisis ipsum. Ut massa justo, porttitor eget erat nec, ullamcorper lobortis magna. Nulla mollis augue lectus. Vestibulum ante leo, faucibus quis egestas vel, luctus quis diam. Maecenas malesuada sem ac elementum iaculis.

Nunc consequat velit sed velit euismod, nec porta mi gravida. Suspendisse vestibulum hendrerit ipsum id ullamcorper. Etiam pharetra diam sit amet lorem aliquam, a hendrerit ante accumsan. Vestibulum nec tellus malesuada, viverra justo nec, convallis urna. In dolor massa, laoreet tristique ornare at, semper quis ipsum. Cras velit enim, iaculis id euismod eget, sagittis a sem. Aliquam dapibus risus eget orci lacinia sagittis non pulvinar dui. Nunc aliquet lacus massa, vitae dictum tortor placerat a. Maecenas sapien lacus, sodales vel erat vel, condimentum accumsan sem. Quisque commodo tincidunt enim id porta. Proin porttitor ornare dolor quis mollis. Nulla facilisi. Vivamus fermentum lacinia augue, feugiat laoreet tortor eleifend in.

Cras ultricies a orci vitae commodo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi in maximus arcu. Aenean pellentesque, magna eu mollis dictum, urna magna pellentesque erat, nec venenatis lorem leo nec sapien. In tempor est massa, ut consectetur ligula feugiat quis. Nunc vulputate magna ac dui imperdiet, a ultricies nibh pulvinar. Nulla facilisi. Suspendisse mi lectus, iaculis vel dui non, ullamcorper sodales libero. Phasellus luctus tellus vitae diam condimentum fringilla. Suspendisse lacinia lacus sed ligula dictum vulputate. Vivamus a nulla sed orci gravida viverra et non eros.

Curabitur tortor justo, volutpat vitae luctus at, congue nec arcu. Quisque et volutpat leo. Aenean volutpat nibh ac ipsum dapibus hendrerit. Nulla tempus est non felis fringilla, quis sodales ex volutpat. Maecenas mauris quam, porttitor a lectus ut, condimentum convallis magna. Maecenas at cursus nibh. Sed porttitor in felis nec pellentesque. Nullam dignissim sodales mi eu faucibus. Etiam elit orci, lobortis quis tellus et, pharetra tristique risus. Etiam eu fringilla nunc, non cursus lorem. Integer vel orci volutpat, tempor lacus quis, finibus mi. Morbi eget leo suscipit, viverra arcu vel, luctus dui. Maecenas eget felis dictum, dictum dolor ut, gravida quam.

In accumsan quam eget mi dapibus, ac posuere lorem elementum. In aliquam ante eu laoreet cursus. Nulla facilisi. Nunc sodales tellus ullamcorper laoreet sodales. Vivamus pharetra est nec dui dictum, in pretium libero egestas. Pellentesque porttitor neque erat, eget scelerisque quam efficitur eu. Nullam ut rutrum tortor. Cras maximus condimentum sapien, sed pellentesque tortor tempor nec. Morbi viverra tortor nec orci lacinia pretium. Mauris ex orci, egestas sed leo sed, porta dictum diam. Nunc non enim at ligula interdum condimentum. Proin auctor lectus sem, nec mollis augue venenatis vel.

Suspendisse et ex diam. Vestibulum placerat, ligula sed accumsan cursus, est erat elementum lorem, in commodo mi eros at eros. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed faucibus dui ac velit molestie, at fermentum nibh fermentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed id purus nibh. Duis purus ante, dapibus nec tincidunt et, sollicitudin et lacus. Nulla mattis nunc dui, eget rhoncus ipsum mattis eget. Aliquam mattis, eros ac placerat semper, risus nisi scelerisque libero, non tempor metus sapien at neque. In hac habitasse platea dictumst. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin at ornare tortor, vel efficitur orci. In pellentesque nisi eget sapien mollis tincidunt.

Mauris molestie in magna in suscipit. Cras placerat convallis sem, at dictum lacus feugiat at. Ut congue nec est sagittis sodales. Phasellus dolor leo, pellentesque vel imperdiet id, hendrerit ut odio. Suspendisse rhoncus tincidunt mauris venenatis lacinia. In nulla turpis, dictum ut urna ac, ultrices porta felis. Cras sem libero, malesuada sit amet nisl sit amet, aliquet porta lectus. Pellentesque felis felis, eleifend non egestas eu, sollicitudin vitae magna. Praesent ultrices, diam eget lacinia rutrum, turpis velit commodo nulla, eget consectetur dui mi in magna. Nunc ultrices imperdiet imperdiet. Aenean pretium lorem vitae cursus placerat.

In a rhoncus orci. Nam vestibulum lectus nec purus pharetra tincidunt. Cras vehicula metus eu efficitur tincidunt. Pellentesque ut lobortis augue, ut tempor felis. Cras dictum odio ut nisl euismod, quis ultrices tortor pharetra. Aenean non lobortis nisi, nec posuere nisl. Vestibulum pretium mollis elit ac consectetur.

In venenatis risus vitae ullamcorper laoreet. Sed aliquam leo id nisi molestie accumsan. Proin vel nibh nec velit faucibus tempus. Vivamus non odio ligula. Nam id felis facilisis nibh maximus volutpat. Vestibulum quis semper magna. Suspendisse tortor elit, pharetra ut ornare vel, commodo sed nibh.

Cras porta fringilla enim placerat scelerisque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Quisque eget nibh et sem laoreet pellentesque. Mauris at mi ut lectus lacinia maximus eu ut diam. Cras non erat eros. Sed blandit, lacus sed aliquet laoreet, ipsum mi tincidunt velit, sed dignissim odio sem ut felis. Curabitur sodales quam et pellentesque pharetra. Sed vel enim vestibulum, maximus justo et, sodales quam. Curabitur ipsum tortor, tristique nec tincidunt a, maximus at massa. Fusce metus metus, maximus quis neque id, interdum cursus felis.

Nam vitae nulla interdum, pharetra diam sit amet, tempor ipsum. In augue ex, luctus vel lacus vitae, scelerisque imperdiet libero. Nunc ac lacinia lectus. Morbi a leo mollis, vestibulum erat eget, sollicitudin nibh. Curabitur volutpat ullamcorper quam, et tincidunt mi venenatis vel. In maximus, diam vel pretium sagittis, nibh ex rhoncus dolor, eget sodales magna arcu ut quam. Nullam dapibus euismod est eu feugiat. Mauris dictum sit amet nulla vel porta. Etiam eleifend leo eget mauris semper blandit. Praesent suscipit, turpis id vestibulum porttitor, eros ex pretium lectus, eu pulvinar orci mauris id lacus. Etiam vel diam sapien. Nam tristique fermentum elit eu scelerisque. Aenean pellentesque lorem a enim sodales, quis malesuada mauris gravida.

Mauris non sapien sit amet eros auctor placerat. Sed libero quam, aliquam et luctus at, imperdiet eget nulla. Cras iaculis nulla nisl, bibendum viverra neque ullamcorper in. Curabitur congue ante fermentum tortor finibus elementum. Sed id tellus ullamcorper, pretium diam nec, suscipit metus. Aenean arcu mauris, tincidunt non tincidunt quis, pulvinar quis ipsum. Phasellus convallis ante a dolor feugiat egestas. Nunc sodales, augue nec egestas rutrum, lacus ante iaculis dolor, ultricies blandit metus lacus non magna. Pellentesque in tellus vitae ipsum iaculis pulvinar sed a risus.

Aliquam iaculis, felis vel aliquam dapibus, ipsum elit pulvinar sem, fermentum ullamcorper velit neque ac mauris. Aenean tellus nibh, gravida nec massa ac, porttitor condimentum lacus. Aliquam sagittis accumsan nisi, quis mollis justo auctor a. Phasellus vitae finibus diam. Vestibulum magna ex, consectetur quis consequat interdum, tempus a diam. Nulla gravida, dui cursus tincidunt viverra, felis nisi dapibus neque, eget tempor quam tortor eget eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Nulla facilisi. Cras et feugiat turpis. Vivamus eget bibendum sem, sed consequat eros. Donec libero felis, consequat a felis sed, interdum eleifend enim. Sed a mollis purus, quis pretium felis. Duis maximus elit odio, eget ullamcorper nibh facilisis vitae. Vivamus lobortis mauris sit amet ligula pretium, id iaculis ligula eleifend. Phasellus egestas diam at mi dapibus pharetra.

Pellentesque consectetur, eros sed congue egestas, lectus ipsum scelerisque lectus, at viverra sem lacus nec orci. Praesent eget fringilla orci. Ut eu aliquet felis, id eleifend ante. Pellentesque ultrices eget velit sed accumsan. Etiam sed aliquet massa, ut dictum tellus. Maecenas pellentesque enim quam, vitae gravida neque faucibus nec. Nulla facilisi. Nullam accumsan quis erat et viverra. Maecenas pellentesque augue at tortor scelerisque hendrerit. Sed metus sem, gravida a pharetra non, auctor eget dolor. Curabitur eget nisi vulputate, luctus lacus ut, egestas leo. Cras semper hendrerit elementum.

Curabitur dapibus tortor finibus, posuere mauris vitae, scelerisque ipsum. Nulla convallis dolor sit amet dui euismod, ac bibendum erat dictum. Aenean orci urna, fringilla ut luctus vitae, lobortis vel quam. Nullam mollis nunc nec mauris porta, a mattis nulla fermentum. Suspendisse potenti. Etiam auctor egestas turpis, nec semper dui condimentum sed. Proin auctor justo non ipsum ornare condimentum fringilla ut ipsum. Aenean id lorem risus. Nullam mauris ipsum, cursus at felis eu, consectetur vehicula felis.

Ut suscipit ipsum nisi, ac accumsan dolor dignissim id. Suspendisse luctus a ipsum eget hendrerit. Aenean non lectus laoreet, tincidunt sapien eget, faucibus enim. Integer eu nibh risus. Duis facilisis mi sit amet nulla tincidunt, fermentum volutpat dolor blandit. Aenean eget dui iaculis, semper nulla eget, pellentesque sem. Suspendisse neque est, porta et consequat tristique, consectetur id erat. Nullam venenatis massa nec ante maximus, non porta lorem dignissim. In non magna hendrerit, vulputate velit in, scelerisque orci. Suspendisse vitae ante leo.

In porta lacus neque, eget volutpat leo auctor et. Donec varius gravida turpis, nec pretium elit consectetur eu. Aenean ut lectus sed elit condimentum consectetur vitae eu leo. Suspendisse et eleifend nulla, aliquam convallis eros. Nullam mollis nulla a facilisis auctor. Donec neque ex, bibendum non augue eu, dignissim pulvinar nibh. Curabitur nec mi sed nisi pellentesque hendrerit eget at est. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam enim erat, pharetra vitae nunc at, dictum tempus risus.

Vivamus pulvinar id augue a ultrices. Cras euismod enim lacus, porttitor aliquet nisl consectetur at. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec a eros orci. Duis faucibus interdum mauris id ultrices. Nullam vitae ex malesuada, hendrerit augue viverra, blandit nulla. Vivamus auctor tellus convallis tellus pellentesque, varius eleifend urna molestie. Maecenas viverra nibh ut nisl pellentesque laoreet. Nunc dapibus ullamcorper imperdiet. Nulla finibus ante massa, ut bibendum nisl dapibus non. Sed quis arcu sed lorem dignissim condimentum sed nec dolor.

Aenean risus lorem, auctor non cursus vitae, tincidunt eu nibh. Duis tellus nisi, lacinia at ligula at, ultricies scelerisque lacus. Donec venenatis elit ac mauris commodo, eu aliquam nunc fermentum. Fusce eget pretium libero. Phasellus vitae mauris sem. Aliquam at nibh mi. Suspendisse id arcu quam. Sed ex enim, luctus vitae malesuada sed, commodo a tortor. Proin eget dolor a eros fermentum posuere vel sit amet nisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam consequat tempus justo, ac tincidunt enim consectetur a. Suspendisse eget vehicula massa. Etiam leo justo, commodo nec condimentum nec, eleifend tempor ipsum. Fusce et faucibus enim, non maximus odio. Nam sit amet eleifend elit.

Maecenas luctus eu ipsum eu posuere. In pellentesque fermentum tincidunt. Duis consectetur gravida sapien id vestibulum. Duis quis vulputate risus. Etiam fringilla in odio at tincidunt. Maecenas vel iaculis eros. Fusce metus velit, vestibulum non tincidunt ut, faucibus vel velit. Aliquam ut felis et libero iaculis sollicitudin. Pellentesque faucibus nec turpis ac laoreet.

Donec nec nisi mauris. Donec luctus quam mauris, non cursus orci pharetra sit amet. Quisque laoreet elit rhoncus velit dapibus auctor. In imperdiet, diam ac pellentesque venenatis, nisl ante hendrerit diam, eu faucibus elit tortor ut magna. Aenean suscipit non erat quis gravida. Sed vehicula tincidunt nisl in consequat. Integer neque elit, commodo a elit sit amet, tincidunt sollicitudin leo. Donec at tincidunt nunc, et porta diam. Aenean suscipit et ex nec ullamcorper. Vivamus ligula nulla, ultrices a odio nec, cursus rhoncus tortor. Praesent et mauris vel mi scelerisque pellentesque. Fusce ultrices lectus ac leo feugiat, eget scelerisque odio interdum. Sed imperdiet mattis vulputate. Vivamus non sapien quis magna euismod fringilla. Pellentesque venenatis consequat eros nec congue.

Praesent varius maximus massa at tempor. Integer erat risus, fermentum at odio vel, lacinia aliquet metus. Nam lacinia quis leo vitae semper. Quisque eget imperdiet diam, eu vestibulum lacus. Proin imperdiet lectus vel ipsum iaculis laoreet. Maecenas posuere neque sit amet lorem mollis facilisis. Suspendisse eu elit erat. Sed feugiat massa ac ligula lacinia, ut convallis arcu elementum. Nunc faucibus quis mi in vestibulum. Nullam ac orci quis dolor suscipit auctor eget a ante. Aliquam sollicitudin turpis et justo scelerisque placerat.

Praesent massa arcu, vehicula non tincidunt a, hendrerit pharetra orci. Aliquam elementum sodales orci, id elementum nisi cursus ac. Praesent efficitur massa ut placerat fringilla. Nullam lacus mi, pulvinar vel hendrerit et, interdum et nibh. Aliquam erat volutpat. Donec pulvinar nibh nec erat congue, eu cursus augue laoreet. Mauris libero felis, porttitor a rutrum sed, molestie id odio. Nunc eros sapien, bibendum at sodales at, fringilla vel neque. Nunc dignissim tristique tempor. Aliquam mattis metus massa, id gravida tellus viverra eu. Phasellus viverra tempor nulla, ac rutrum dolor vulputate a. Etiam lacus risus, facilisis tincidunt eros ut, euismod elementum est. Nunc rutrum fringilla lacus a finibus. Suspendisse potenti.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas a sollicitudin dui. Aenean diam risus, pulvinar a elit a, sagittis varius quam. Aenean tincidunt tempus facilisis. Mauris interdum urna vel efficitur tempus. Maecenas convallis rhoncus felis eget euismod. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In eu quam sit amet lectus suscipit tempus vitae sit amet justo. Donec sollicitudin porta nisl, at aliquam ex blandit a. Sed non efficitur sem. Praesent sapien quam, condimentum nec dui sed, gravida hendrerit augue. In condimentum sollicitudin ligula a egestas. Etiam eu sem mollis, eleifend massa eu, gravida ante. Proin vel placerat ligula, vel ultrices nisi. Duis et mauris maximus mi eleifend lobortis eu eu libero. In sit amet libero id metus luctus venenatis.

Curabitur bibendum fermentum posuere. Pellentesque tempus, sem a elementum tempor, enim erat cursus est, at aliquam mauris libero ut est. Nam sed nulla a odio dignissim commodo. Praesent quis tellus lacus. Morbi facilisis ante non dolor luctus, id ornare leo molestie. Donec et magna placerat, placerat urna et, tempus est. Sed rhoncus lorem eget hendrerit mattis. Suspendisse elementum dolor sed augue porta, a consequat risus malesuada. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean vehicula rutrum nisl. Quisque metus nulla, convallis non tellus nec, auctor vulputate nisi.

Aliquam malesuada, justo et varius commodo, nibh neque posuere arcu, eu convallis sapien dolor quis urna. Aenean sed vestibulum est. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec rutrum libero euismod nisl gravida, sed sodales velit euismod. Curabitur at posuere eros, sed blandit nulla. Mauris quis ipsum quis diam laoreet convallis a a quam. Suspendisse molestie ipsum vitae scelerisque elementum. Nullam mi enim, vulputate vel lectus id, convallis tempor nibh. Ut et volutpat massa, in efficitur sem. Donec in commodo odio.

Vivamus molestie turpis eu ex luctus blandit. Proin porta, velit in ultrices ornare, nibh leo mollis lectus, sed pharetra turpis justo vel est. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi fringilla magna vel nibh iaculis tristique. Suspendisse et sem porttitor turpis maximus fringilla a eu enim. In hac habitasse platea dictumst. Aliquam erat volutpat. Vivamus rhoncus erat quam, quis eleifend justo viverra eu. Nullam vitae dignissim erat, id varius nulla. Phasellus pretium pharetra sem vitae viverra.

Morbi eros nibh, fermentum id justo in, dignissim dignissim elit. Suspendisse semper ante sagittis, ornare magna at, elementum erat. Praesent at magna vulputate risus mattis facilisis euismod vel augue. Pellentesque pellentesque tortor ut tortor iaculis, at bibendum augue viverra. Pellentesque id libero volutpat, mattis quam eget, porttitor ipsum. Quisque ornare eu velit vel iaculis. In pulvinar id odio in sollicitudin. Ut vestibulum quam sit amet mi vulputate, ac aliquet dui consectetur. Fusce tempus tincidunt diam vel imperdiet. Nullam quis auctor erat, et venenatis ex. Nunc vel vehicula turpis, non sollicitudin nisl. Nulla non bibendum mauris. Quisque ut ante vehicula, pulvinar leo vel, malesuada diam. Curabitur laoreet sit amet nibh id maximus. Donec odio sem, consequat sit amet luctus quis, efficitur quis turpis.

Curabitur lacinia, ligula ac pellentesque interdum, lectus dui pulvinar enim, non aliquam massa sapien in nisi. Mauris vehicula urna ac dolor finibus venenatis eget sit amet tellus. Cras et sagittis elit. Etiam in commodo nibh, vitae porta orci. Cras eget nisl varius, tristique risus ac, dictum neque. Sed consectetur maximus ex, a imperdiet nisl pulvinar nec. Aenean pellentesque malesuada erat, a fringilla lorem aliquet id.

Aenean vitae sodales odio. Nullam at purus sem. Quisque tristique, erat at tincidunt sodales, mi ligula ullamcorper tortor, sed condimentum arcu est ut risus. Phasellus eleifend dui urna, ac dapibus leo hendrerit eget. Maecenas eu metus lectus. Curabitur eu imperdiet orci. Integer non semper odio. Vivamus elementum tellus a tellus accumsan efficitur. Proin maximus, diam ac venenatis mattis, erat libero maximus ante, non ullamcorper velit ipsum ac neque. Mauris consectetur pellentesque ligula non feugiat. Fusce interdum hendrerit velit ut condimentum. Suspendisse et efficitur justo, eget blandit erat. Suspendisse risus ex, lobortis sed dolor non, ullamcorper luctus est. Vivamus leo sapien, rhoncus vitae pellentesque viverra, accumsan sed risus. Pellentesque consectetur, quam vel hendrerit dapibus, magna lacus malesuada diam, vel semper leo lorem rutrum dolor.

Integer sed accumsan enim. Donec erat nunc, consectetur nec ipsum at, eleifend condimentum mauris. Donec lectus ex, dictum nec molestie sodales, fringilla sit amet risus. Sed eu quam eget enim cursus luctus. Mauris non erat eu orci vulputate dictum. Pellentesque dapibus mattis sapien, eu sollicitudin ex commodo eget. Integer vitae bibendum nunc, sed sollicitudin orci. Vivamus convallis augue ipsum, non suscipit eros egestas eget. Nam fringilla laoreet libero. Donec rhoncus nisl justo, vel condimentum felis interdum ac.

Quisque varius luctus metus non varius. Sed ante nunc, egestas ac vulputate eu, vulputate in ante. Aenean rutrum ligula eget suscipit elementum. Nulla elementum congue accumsan. Sed pellentesque magna non suscipit molestie. Curabitur convallis ante quis justo scelerisque, eget gravida ligula hendrerit. Phasellus et nisi non risus pulvinar varius vitae sit amet odio. Ut elementum venenatis maximus. Praesent sollicitudin feugiat efficitur. Integer efficitur consequat vulputate. Fusce finibus rutrum orci, non tincidunt ipsum lacinia nec. Phasellus consectetur mollis metus id ornare. Phasellus tincidunt euismod justo sed gravida.

Nunc sit amet tempus metus. Aliquam vel est interdum, lobortis augue sit amet, consectetur lectus. Nam efficitur luctus est eget interdum. Aenean accumsan nulla ac leo maximus pharetra. Vestibulum diam libero, tristique sagittis velit sed, pharetra bibendum est. Praesent et pulvinar ligula. Proin molestie sem ut quam consectetur pharetra. Mauris placerat elit vitae sem laoreet, convallis faucibus urna volutpat. Nulla posuere eros porta metus feugiat, quis ornare orci pretium. In ac tortor magna. Nam erat nunc, ullamcorper eget venenatis ac, facilisis feugiat turpis. Morbi egestas lorem ac justo vehicula cursus. In suscipit ullamcorper mauris ac aliquet.

Quisque porttitor, lectus sed ultricies tempus, tellus leo tincidunt velit, eget porttitor justo sapien vel neque. Fusce in magna eget tellus tristique varius sollicitudin at justo. Curabitur porta mauris quis nulla suscipit, non ultrices ex suscipit. Praesent vitae libero mollis, faucibus odio lacinia, sollicitudin dui. Nulla blandit auctor arcu sed congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin cursus mollis lorem, sit amet semper lacus feugiat a. Nullam risus nisi, volutpat ut tincidunt ac, euismod eget lectus. Ut euismod turpis rutrum vehicula malesuada. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus tempus, enim a pretium elementum, urna augue ultricies eros, sed interdum dui quam sit amet velit. Donec metus justo, ultrices quis lectus vitae, aliquam dictum metus. Praesent vehicula lorem at blandit tristique.

Suspendisse potenti. Suspendisse eget mi eu nisi rutrum malesuada quis placerat felis. Proin mi massa, pretium ac aliquam sit amet, posuere in risus. Nullam odio erat, elementum in molestie at, malesuada vitae ex. Duis quis fringilla mauris. Maecenas vulputate faucibus lacus vitae tristique. Aliquam egestas congue magna, vel malesuada leo fermentum id. Fusce gravida et ante sit amet rutrum. Maecenas id ante urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id iaculis tellus. Aliquam tortor nisi, ullamcorper a lorem sed, bibendum mollis diam.

Duis elementum, mauris vitae sodales tempus, enim turpis rutrum felis, vitae facilisis nisi quam nec ex. Duis et vehicula est. Praesent vitae tristique sem, faucibus facilisis ligula. Ut a rutrum nisi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur consectetur dolor at gravida euismod. Donec et egestas tellus, vel sagittis justo. Mauris molestie quis tellus nec porta. Ut porta blandit ligula quis vehicula. Phasellus sagittis, enim ut mollis iaculis, eros metus volutpat enim, in auctor tellus ipsum vel massa. Donec tortor turpis, semper sed eros id, porttitor egestas enim.

Donec eget sapien sit amet erat viverra elementum vel et est. Praesent quis turpis facilisis, finibus dui vel, pharetra arcu. Integer bibendum mauris mi, vitae lobortis ipsum rutrum quis. Ut et ornare ipsum, ut pretium orci. Nulla eleifend vel massa eget dapibus. Curabitur ac commodo mi. Quisque venenatis eros nisl. Cras tincidunt maximus nibh consequat luctus. Nunc in nibh nisl. Nulla dictum, odio eget laoreet convallis, nisi lacus consectetur augue, eget lobortis orci nunc ut arcu.

Vivamus eu nisi porta massa ornare euismod. Donec ullamcorper, lectus vel convallis porttitor, leo lectus accumsan urna, eget condimentum est est id tortor. Vivamus interdum consequat elit, quis varius sem. Praesent pharetra sem non cursus consectetur. Sed ultrices dictum justo, sed mollis lacus hendrerit eget. Sed purus ipsum, dictum ut sem congue, pretium commodo eros. Aenean tincidunt pellentesque tortor vitae vehicula. Fusce nec imperdiet libero. Cras ac enim dui. Donec maximus varius ipsum ac rutrum. Ut suscipit dapibus vulputate. Donec nulla quam, ornare eu sagittis ac, auctor eget dui. Ut pulvinar urna eget lorem laoreet, a tristique neque feugiat. Sed imperdiet posuere nulla.

Nullam volutpat lorem eu libero finibus dapibus. Aliquam volutpat mi eu eros aliquam, vel ultricies quam placerat. Vestibulum auctor lacus eget dolor molestie finibus. Vestibulum eu erat quis ex aliquet maximus eu vel dui. Ut quis mi suscipit, lobortis metus tristique, vulputate est. Fusce finibus ultrices orci nec efficitur. Nulla id ornare ipsum. Pellentesque ex risus, porta non dictum ac, bibendum id ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam at odio nisi. Cras mollis, mi non rutrum efficitur, ex felis cursus quam, ut pharetra eros odio et lorem. Mauris viverra nisl ut nisl porttitor, efficitur gravida libero fringilla. Ut quis vehicula dui, sed maximus sem. Ut finibus faucibus odio, tempor sollicitudin ex blandit non. Mauris cursus nunc eros, sit amet mollis sapien euismod eu. Vivamus nisi nisl, ultricies sit amet est nec, porta tempus magna.

Aliquam a ipsum eros. Praesent eget mattis quam, sed ultrices metus. Sed quis lobortis mauris. Aliquam erat volutpat. Quisque lectus metus, tempus vitae arcu eu, condimentum consectetur odio. Mauris lectus felis, porta at efficitur sit amet, tristique ac est. Etiam varius dolor eu maximus elementum.

Nulla facilisi. Praesent ac pharetra quam. Nam id aliquam turpis. Nulla finibus vel sem a vestibulum. Donec vitae sapien eu urna lobortis mollis quis quis lorem. Ut quis erat id arcu tincidunt vulputate. In in ipsum quis augue sagittis dapibus nec eget ipsum. Aenean maximus scelerisque dignissim. Mauris a sem suscipit, aliquet orci at, malesuada orci. Donec posuere mauris lectus, sed gravida dui feugiat sed. Sed metus dui, ullamcorper vitae posuere bibendum, pretium non dolor.

Nulla fringilla eros in est elementum, sit amet maximus turpis dictum. Nullam id vulputate mauris. Quisque vestibulum tortor id leo venenatis sagittis. Sed in augue quis augue eleifend suscipit sit amet sed arcu. Donec sollicitudin facilisis magna a facilisis. Suspendisse a dui dictum, posuere massa vitae, congue justo. Integer sed arcu a magna bibendum tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam in vehicula purus, nec scelerisque nisi.

Curabitur eu risus non lacus ornare hendrerit. Maecenas eu lacus at ligula iaculis lacinia. Praesent quis porta lacus, sit amet consequat diam. Donec id dapibus metus. Cras ornare lectus sit amet mi vestibulum, eget laoreet tellus pellentesque. Sed neque metus, cursus quis bibendum a, porta eu quam. Suspendisse egestas nunc nec metus sagittis, ac commodo orci pulvinar.

Quisque pulvinar varius bibendum. Etiam eros urna, lobortis at dictum et, efficitur sed nunc. Etiam a feugiat velit, sit amet posuere enim. Phasellus in posuere nisi. Integer eu velit mollis, blandit eros non, consectetur augue. Nullam sem nunc, porttitor et urna ac, mattis egestas justo. Quisque efficitur pretium blandit. Quisque commodo, nulla id viverra hendrerit, velit metus tempus elit, eu finibus turpis purus eget orci. Integer dignissim elementum ante eget auctor. Ut vulputate justo turpis, at viverra nulla egestas tempus. Praesent non fermentum tortor. Praesent non pellentesque nibh.

Maecenas posuere tincidunt nibh, at vulputate ante vehicula sit amet. Nunc consequat ante tortor, a posuere est maximus nec. Maecenas magna ex, hendrerit eu eros sed, viverra congue turpis. Integer erat nisl, iaculis nec elit a, lacinia pellentesque urna. Proin sed condimentum magna. Donec vitae nisi vel massa ultricies auctor. Morbi eget rutrum sapien, in egestas eros. Vivamus nisi elit, euismod a nunc et, porta maximus velit. Nunc dolor mauris, imperdiet vel bibendum sit amet, molestie quis est. Pellentesque sollicitudin venenatis neque et fringilla. Curabitur ac erat iaculis, convallis ligula non, egestas libero. Suspendisse ultrices laoreet lacus, sed hendrerit elit molestie vitae. Pellentesque condimentum ante odio, vel ornare quam lobortis non. Aliquam convallis tempor nisi non mattis. Vestibulum finibus lacus nec neque commodo sollicitudin.

Quisque mi orci, bibendum quis aliquet et, dignissim hendrerit lacus. Duis in turpis iaculis, auctor arcu at, maximus leo. Sed ac efficitur eros. In vehicula metus ut venenatis sollicitudin. Quisque at efficitur urna. Vivamus feugiat, enim ac semper ultricies, orci neque porta lorem, fermentum pretium mauris diam sed elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed augue orci, dapibus nec hendrerit nec, cursus ac dolor. In hac habitasse platea dictumst. Suspendisse accumsan urna enim, et aliquam lacus pellentesque vitae. Suspendisse potenti. Mauris sit amet dui imperdiet, congue ex vel, dictum lacus. Praesent mollis, felis a tempus convallis, lorem velit viverra massa, sit amet semper odio neque vitae ex.

Fusce maximus vulputate odio, ac condimentum sem pellentesque sit amet. Donec suscipit arcu eget malesuada suscipit. Sed vel nibh nec ex elementum dictum et quis erat. Nulla sollicitudin odio bibendum lectus vulputate lobortis. Donec id odio vel dolor ultricies dapibus. Quisque lacinia tincidunt augue ut semper. Cras aliquam, orci non pharetra efficitur, risus odio convallis mi, ac interdum dui est eget eros. Aliquam convallis consequat sem, ac consectetur erat ultricies ut. Aliquam egestas dolor sed mi pulvinar viverra. Nam aliquet condimentum efficitur. Morbi tristique finibus tortor, commodo sagittis erat dictum at.

Nam sagittis non elit ac auctor. Pellentesque efficitur magna vitae nisi pellentesque malesuada. Ut rutrum tortor massa, a sodales nisl sodales vel. Donec mauris justo, finibus eu nisl dapibus, lacinia mollis neque. Phasellus placerat ac nisi et tincidunt. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla molestie vel justo eu imperdiet. Quisque finibus nunc eget sapien faucibus, at eleifend erat imperdiet. Vestibulum tristique rhoncus orci ac pharetra. Duis porta ligula vel neque rhoncus, nec accumsan nibh gravida. Phasellus sed purus vel augue volutpat suscipit. Proin placerat ex erat, ut condimentum est hendrerit id. Cras aliquet ullamcorper tortor quis ornare. Donec iaculis, odio vitae accumsan fringilla, augue urna commodo tortor, eu tempor urna tortor eu tellus. Maecenas at enim tempus ligula porta sollicitudin non at quam.

Ut efficitur tortor pretium nulla vehicula venenatis. Cras in risus ac erat hendrerit egestas et vel nulla. Nunc dignissim nisi non leo tempor elementum. Fusce quis placerat dui. Aenean imperdiet quam vitae interdum pharetra. Praesent tempus nulla sem, ut aliquet sapien mollis id. Sed finibus vel erat ac sodales. Sed aliquet sapien ex, sit amet maximus justo vulputate nec. Etiam et lacus ac dolor sollicitudin rutrum sagittis nec purus. Integer pretium magna at turpis eleifend convallis. Etiam id est a massa congue euismod. Aenean mi felis, hendrerit nec odio non, eleifend imperdiet ipsum.

Vestibulum quam nunc, tincidunt ac posuere eget, mollis quis felis. Sed in justo est. Etiam in euismod erat, nec laoreet quam. Nullam at ullamcorper risus. Curabitur congue a augue eu dictum. Fusce varius neque quis nibh egestas, non gravida massa tincidunt. Donec odio urna, efficitur vitae mi ac, fermentum lacinia purus. Sed erat mauris, blandit quis rhoncus non, interdum vitae nunc. Ut vestibulum rutrum velit, at semper nisl tristique at. Nulla tempus, erat sit amet imperdiet rutrum, mauris nunc rutrum sapien, a egestas dolor risus non metus. Quisque sagittis magna in viverra maximus. Aenean laoreet in purus et scelerisque. Pellentesque sit amet dui vitae nulla vehicula ullamcorper.

Donec dictum lectus at ipsum pretium dapibus. Donec sed libero egestas, commodo tellus nec, mattis diam. Praesent tristique, nunc eu accumsan accumsan, sem justo interdum lectus, a mattis lectus tellus sed lectus. Quisque quis semper mi, pulvinar aliquam erat. Phasellus leo metus, scelerisque in efficitur eget, accumsan nec nunc. Curabitur condimentum eget sem feugiat pharetra. Maecenas feugiat consequat ullamcorper. Nulla auctor aliquet orci, at tempor nibh auctor quis. Aliquam porttitor tortor quis eros dignissim auctor. Nulla ullamcorper nibh eu sodales porttitor. Maecenas vel turpis non erat hendrerit venenatis vel sed magna. Ut sed turpis malesuada, finibus sapien nec, ornare nisl. Suspendisse mi enim, dapibus euismod tempus at, sollicitudin eu ex. Nam imperdiet non risus quis faucibus. Etiam ultrices ex et neque malesuada, vitae gravida neque sollicitudin. Duis nec congue velit, placerat rhoncus velit.

Nunc congue nec purus a efficitur. Sed ut sagittis magna. Morbi maximus eget ante id vehicula. Proin id dui et est vulputate pretium. Integer eget viverra ex. Mauris ut eros cursus, rhoncus libero eu, sollicitudin enim. In dui nulla, blandit ut aliquet non, sodales ac felis. Integer ac ex nec neque accumsan eleifend. Sed in orci sit amet urna laoreet convallis nec vel nulla. Vestibulum sapien est, semper vitae mollis at, mattis a felis. Maecenas cursus egestas semper. Nunc iaculis sodales dictum.

Morbi nec consequat ante. Pellentesque volutpat lectus risus, id facilisis nisl auctor quis. Proin sed turpis at lectus imperdiet viverra vel eget nulla. Phasellus ultrices accumsan mauris fermentum ullamcorper. Curabitur ut tincidunt diam. Etiam erat neque, commodo sed sapien id, luctus faucibus felis. Maecenas ullamcorper, ligula sed finibus hendrerit, sem justo auctor dui, eu mollis augue massa ac leo.

Duis pharetra malesuada velit ac rutrum. Nullam in auctor urna. Maecenas mollis faucibus orci, ut aliquet dolor imperdiet at. Maecenas commodo blandit nibh, in porta quam. Nullam eleifend neque id libero euismod, sit amet aliquam magna lacinia. Curabitur rutrum quam non tempus sollicitudin. Ut ultricies nunc quis dui fringilla, non gravida urna mattis. Phasellus ut libero odio. Nullam eget rutrum risus. Suspendisse potenti. Sed at lacinia ex. Vestibulum elementum lacus tempor tincidunt venenatis. Proin convallis sapien ipsum, eget tincidunt mi hendrerit ut. Nunc condimentum posuere lacus, eu ultrices massa fringilla in.

Curabitur et libero convallis, lobortis urna ac, lacinia risus. Integer consectetur mauris id erat cursus, sed mattis odio aliquam. Ut sed fermentum risus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce imperdiet augue nisl, eget viverra ex ullamcorper quis. Donec vestibulum augue sed facilisis faucibus. Integer lectus tortor, lobortis vel elementum eget, volutpat sit amet justo. Pellentesque viverra tempor nisi, nec imperdiet sapien semper sit amet. Cras in turpis nec mi imperdiet finibus faucibus quis diam. Nunc tortor nibh, finibus vel risus et, mattis cursus odio.

Nullam sed sodales orci, vitae rhoncus lacus. Nulla dapibus maximus elit, gravida rhoncus metus ornare in. Curabitur elementum est lorem, quis auctor eros fermentum et. Cras iaculis, dolor tempus iaculis molestie, erat nibh pharetra ante, nec pretium quam nisi sit amet massa. Etiam vitae consequat elit, eget pharetra nisl. Quisque ornare leo nisi, id malesuada tortor feugiat et. Aenean odio lectus, faucibus non porttitor non, commodo sed mauris. Donec lacinia condimentum fermentum. Aenean gravida nec sapien viverra dapibus. Sed faucibus ac odio id auctor. Maecenas non erat sed augue posuere ornare. Etiam ultrices orci eget nulla laoreet, ac rhoncus nisi accumsan. Praesent id felis eget ex finibus placerat et nec dui. Phasellus dignissim, ante id mollis tristique, magna massa viverra arcu, ac interdum felis tellus a sapien. Nulla facilisi. Sed vulputate ex libero, at ultricies sem porta sed.

Ut dapibus purus placerat massa porta placerat ac sed turpis. Suspendisse viverra facilisis condimentum. Donec sed magna a turpis blandit tempus ac quis diam. Donec imperdiet felis at elit viverra, at volutpat ex elementum. Nunc dolor metus, hendrerit sed iaculis quis, ultrices ac orci. Nam tincidunt justo sollicitudin consectetur blandit. Donec lacinia turpis massa, id auctor nulla faucibus sed. Sed ut elit dapibus, tincidunt purus id, blandit mauris.

Etiam quam est, scelerisque et risus id, luctus sagittis arcu. Nunc sed mi molestie, condimentum velit ultrices, auctor nunc. Praesent rutrum arcu ac neque sollicitudin, eu egestas ipsum lobortis. Curabitur egestas justo at pretium condimentum. Etiam efficitur massa dui. Curabitur fermentum metus neque, sed porttitor felis pharetra et. Phasellus imperdiet tempor risus, id semper mauris venenatis et. Sed in aliquet sem, ut venenatis dui. Suspendisse a elit fermentum, suscipit diam sed, fermentum nibh.

Praesent vestibulum tortor lacus, vel tincidunt velit posuere aliquet. Cras vehicula leo sit amet sapien eleifend, eu lacinia ligula egestas. Vestibulum iaculis libero vitae sollicitudin faucibus. Etiam vel mauris sit amet arcu egestas suscipit in in metus. Ut tristique bibendum est rutrum tempus. Aenean eu iaculis lectus, et ornare metus. Ut varius nunc sapien, a cursus ex malesuada id. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nunc erat dui, efficitur nec volutpat sed, fermentum id metus.

Quisque lobortis pharetra orci ut molestie. Praesent semper pellentesque odio. In a cursus nibh. Cras volutpat urna nec felis auctor laoreet. Vivamus nisi augue, dapibus vitae lobortis vel, elementum id erat. Vivamus a lacus mi. Aliquam ullamcorper pretium pharetra. Mauris venenatis magna ac orci lobortis, sed interdum purus dapibus. Donec dictum, lorem ac egestas pretium, ipsum erat eleifend justo, vitae laoreet ligula nibh sit amet elit.

Integer hendrerit quis mauris quis vehicula. Mauris magna ipsum, placerat non odio non, porttitor volutpat orci. Integer aliquet lorem id nunc porttitor, sed porttitor diam rhoncus. Fusce mollis tempus tortor suscipit pellentesque. In sollicitudin non massa in semper. Quisque faucibus dictum est at varius. Duis placerat lectus magna, at viverra ligula tincidunt eget. Donec venenatis vitae massa eu bibendum. Morbi id massa ac felis viverra posuere vel efficitur mi. Vivamus tristique consequat metus, eget lobortis odio feugiat eget. Phasellus luctus, elit quis laoreet consectetur, orci quam mattis ante, sit amet dapibus mi lorem euismod nibh.

Ut volutpat ipsum purus, ut tristique nulla imperdiet placerat. Vestibulum sapien felis, congue non magna et, lobortis accumsan lacus. Vivamus facilisis tellus at scelerisque sagittis. Curabitur rhoncus bibendum est quis efficitur. Suspendisse accumsan fermentum neque quis consequat. Nunc laoreet sapien justo, id auctor lorem vulputate pharetra. Sed elementum fringilla euismod. Nulla vestibulum ante magna, nec malesuada ante venenatis at.

Nunc vehicula pretium mi et viverra. Mauris id sapien nisi. Vivamus enim dui, tempor eu velit tempor, varius facilisis dolor. Phasellus purus lectus, pharetra quis libero at, eleifend consequat orci. Duis tincidunt vel orci quis feugiat. Nunc nec mi ut metus pellentesque ultrices et eget justo. Nam mollis convallis fermentum. Sed sed diam sit amet eros laoreet dictum. Proin quis dapibus nisl. Donec efficitur aliquam erat dignissim mattis. Aliquam odio urna, scelerisque sit amet malesuada at, ornare quis nibh. Proin cursus nibh posuere vehicula sagittis. Phasellus facilisis felis a interdum malesuada.

Aenean nec congue lorem. Nulla laoreet egestas nulla, nec pulvinar lacus pellentesque non. Suspendisse potenti. Sed efficitur ullamcorper neque vel iaculis. Aliquam nisi felis, suscipit non congue vel, cursus non turpis. Sed vestibulum, erat non fermentum ornare, urna leo pellentesque dolor, non ullamcorper justo nisl vel neque. Mauris accumsan nunc sit amet pretium bibendum. Suspendisse semper tincidunt nisl, ut consequat metus rutrum at. Nulla feugiat purus diam, vel bibendum ipsum tristique ut. Suspendisse vel ligula eu velit ultricies pulvinar.

Proin sagittis suscipit odio. Suspendisse vitae enim nibh. Maecenas diam dui, accumsan vel nunc nec, facilisis vehicula ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam sollicitudin mauris eget ante convallis aliquam. Maecenas finibus, ex id tempus porta, lorem nulla euismod tortor, eu rutrum quam eros vel magna. Suspendisse ac consectetur diam, vitae tempor mi. In in leo vel augue sagittis sagittis. Duis vel lorem dictum, congue ante in, mollis augue.

Maecenas tempor lobortis porttitor. Proin mollis lacinia ipsum. Phasellus et pellentesque justo. Donec auctor venenatis tellus et posuere. Suspendisse potenti. Donec sem lacus, accumsan vitae nulla eget, consectetur aliquam diam. Aliquam massa mi, elementum eget ornare placerat, rutrum pharetra dui. Mauris feugiat massa sit amet dictum hendrerit. Sed eros leo, imperdiet in dolor sit amet, varius faucibus lacus. Vestibulum et enim tortor. Aenean mattis nec arcu in iaculis. Proin commodo, leo non porttitor tristique, lectus elit venenatis dui, nec interdum ligula nisl in lacus. Integer elit tellus, consectetur ut ipsum et, egestas malesuada ex. Nunc porttitor interdum ullamcorper.

Suspendisse condimentum feugiat justo in rhoncus. Nam velit diam, hendrerit non viverra eu, sollicitudin sed ante. Phasellus varius euismod odio, a venenatis urna blandit vitae. Nunc lobortis dolor eget pellentesque accumsan. Vivamus quis faucibus urna, quis consequat magna. Mauris eu justo sapien. In porta ipsum sapien, a mattis erat imperdiet cursus. Aliquam orci tellus, dapibus aliquam ante in, laoreet condimentum purus. Ut euismod convallis enim in scelerisque. Donec suscipit eleifend odio, id finibus sapien tincidunt vel. Curabitur hendrerit dui magna, nec cursus lacus vestibulum sit amet. Nunc ut accumsan dolor. Mauris sit amet lectus eros. Quisque vitae vestibulum sapien. Cras ultricies arcu dolor, eu tristique sem vehicula sed.

Duis sagittis efficitur lacus. Ut justo justo, bibendum accumsan risus sit amet, sodales viverra arcu. Fusce nec elementum tortor, eget tincidunt ligula. Integer euismod neque eu fermentum iaculis. Praesent rhoncus quam lacus, nec condimentum tortor fringilla eu. Quisque aliquam urna ac venenatis lacinia. Duis dignissim neque magna, in iaculis nisi ornare quis. Donec tempor, mi et molestie eleifend, dolor leo maximus mauris, id fermentum sem ex ac tortor. Nunc tristique, ex in mattis consectetur, libero est venenatis enim, molestie lacinia metus lectus a augue. Sed quam lorem, porttitor quis suscipit eu, dictum vitae lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean semper molestie consectetur. Nulla tristique lacus sed ligula scelerisque tincidunt. Maecenas in commodo neque.

Maecenas faucibus ante sodales ligula iaculis ultricies. Donec scelerisque imperdiet efficitur. Suspendisse laoreet libero et tincidunt pellentesque. Phasellus semper placerat hendrerit. Ut sollicitudin diam tortor, nec tristique massa convallis vel. In in justo consectetur, dapibus tortor in, dictum orci. In quis nibh in felis posuere aliquet. Aenean quis dui ac magna faucibus auctor non ac neque. Nulla congue posuere magna, vel pellentesque ligula sodales varius. Integer at libero a quam lobortis suscipit. Vestibulum tempor mi et turpis pulvinar, quis gravida velit congue.

Nulla feugiat sapien nulla, et consequat neque efficitur at. Suspendisse vitae lectus ut arcu viverra pellentesque sed ullamcorper nisi. Sed porta blandit libero nec faucibus. Nunc dictum commodo orci non faucibus. Nunc ac nibh nunc. Nulla vitae ligula egestas enim interdum euismod. Duis at diam id urna placerat tincidunt a eget tellus. Cras porta, ante non porta sodales, urna urna vulputate urna, nec mollis nunc elit ut ipsum. Curabitur eget porta diam. Fusce blandit libero sapien, a malesuada augue ornare et. Aliquam erat volutpat. Donec lacinia, lectus vel blandit luctus, nisi mauris pulvinar tortor, sed facilisis felis risus vitae leo.

In placerat urna vitae egestas faucibus. Nulla varius erat eu velit mattis, et iaculis sem rhoncus. Sed pretium est ac metus consectetur ullamcorper. Morbi tristique tellus vitae est gravida rhoncus. Maecenas iaculis ultricies ultrices. Nam nunc neque, tincidunt sit amet facilisis et, efficitur at nibh. Maecenas ac arcu magna. Nunc nulla purus, ullamcorper nec purus ac, porta viverra elit.

Ut a fermentum diam. Donec eu nibh interdum, lacinia neque nec, feugiat tellus. Pellentesque scelerisque elementum varius. Vivamus sed tincidunt odio, sit amet iaculis augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc eleifend molestie metus. Cras feugiat, sem ac pretium vulputate, metus augue mattis enim, eget vehicula mauris velit ullamcorper elit. Maecenas sagittis tellus non convallis faucibus. Nam convallis, lacus nec malesuada cursus, enim nulla semper massa, eu rhoncus lectus enim quis risus.

In hac habitasse platea dictumst. Nulla blandit ullamcorper diam nec tincidunt. Nullam id mattis nunc. Duis euismod mauris non interdum vehicula. Ut fringilla lacinia eros, quis sollicitudin massa accumsan vitae. Donec vestibulum ante eget velit molestie, non posuere orci tempus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas vel risus et nibh blandit pharetra vel vel tellus. Etiam tristique, ligula non facilisis vulputate, lectus turpis dictum dolor, et egestas augue est rhoncus purus. Vestibulum tortor nulla, condimentum et nunc non, sollicitudin vehicula erat.

Sed massa urna, elementum tristique malesuada sit amet, egestas consequat nisi. Nullam ut ultricies neque. Praesent nibh elit, tristique at tempus a, elementum eget nunc. Aenean sit amet varius nibh. Donec nisi sem, pulvinar nec risus porta, faucibus ultricies ligula. Etiam in ante sit amet diam dignissim sagittis non id felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris in placerat ipsum. Donec vel interdum leo. Quisque quis sagittis erat. Morbi vestibulum vel metus in lacinia.

Vivamus nec iaculis ipsum. Aliquam erat volutpat. Sed finibus lectus dui, nec auctor ipsum molestie vitae. Etiam et enim venenatis odio convallis bibendum vitae a sem. Aenean finibus lacus leo, sed finibus augue euismod ac. Sed lobortis risus non dui gravida, non scelerisque massa iaculis. Suspendisse aliquet sagittis mauris. Integer placerat, erat non tristique vulputate, lacus tortor posuere mi, sed condimentum purus quam at massa. Praesent orci ante, imperdiet sed fermentum eget, semper sit amet ipsum. Donec et pellentesque leo. Nunc sit amet scelerisque leo. Maecenas cursus bibendum eros eget lobortis. Pellentesque egestas ullamcorper porttitor. Phasellus mattis ultrices malesuada.

Duis bibendum, orci at fringilla placerat, quam lacus lacinia ipsum, et aliquam augue sem ullamcorper lectus. Donec pretium massa elit, ut posuere mauris tempus quis. Proin lobortis convallis tincidunt. Ut mattis feugiat diam, a scelerisque risus tempus finibus. Sed bibendum sodales nisi, sed rhoncus neque ultrices a. Fusce euismod porttitor ligula nec pellentesque. Sed lobortis consequat egestas. Fusce rutrum eleifend nisi id molestie. Sed a libero faucibus, ullamcorper sapien condimentum, tincidunt turpis. Sed congue semper sagittis. Ut in neque nec est efficitur mattis scelerisque sit amet diam. Sed orci massa, mattis at elit non, euismod sodales elit. Donec tempor metus ante, eu volutpat leo placerat sit amet. Suspendisse aliquam vel purus vitae pretium. Proin elit purus, gravida sit amet maximus vitae, fermentum at neque.

In justo tortor, blandit sit amet ligula quis, venenatis suscipit eros. Nam ut quam porta, efficitur justo in, posuere orci. Nullam vehicula vitae quam a laoreet. Fusce feugiat justo quis tincidunt dictum. Aenean ut eros nec arcu maximus tempor quis nec velit. Etiam dui risus, scelerisque quis magna accumsan, lacinia consectetur tellus. In vitae massa pellentesque diam rhoncus faucibus ut et orci. Nulla et orci vitae massa vulputate molestie ultricies at enim. Sed tempor lorem quis rutrum condimentum. Duis commodo tempor enim id congue. Vivamus velit orci, egestas eu risus nec, varius convallis nulla. Nulla arcu urna, laoreet eu leo ut, gravida finibus sem.

Fusce a diam non leo posuere aliquet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla vel nisi pharetra, sodales urna eu, vulputate eros. Aenean faucibus bibendum orci ultricies fermentum. Integer dignissim lorem semper, sollicitudin augue in, gravida tortor. Ut eget nisl congue, venenatis mauris sit amet, ornare tellus. Vestibulum justo mi, pulvinar sed luctus eu, eleifend ut nisl. Maecenas orci eros, tempus nec quam eu, lacinia dictum massa. Nam sodales elit lacus, eu tristique nisi tristique vitae.

Duis dapibus, elit ut consectetur pretium, metus dui aliquet odio, id pellentesque ante odio vel risus. Nam commodo maximus finibus. Suspendisse lectus sem, pellentesque sit amet nunc sit amet, facilisis congue arcu. Curabitur eget elementum nunc, in ullamcorper ex. Vivamus feugiat ex nunc, sed viverra massa ornare sed. Mauris gravida odio sed faucibus condimentum. Maecenas ullamcorper condimentum ligula. Vestibulum commodo rutrum interdum. Cras nec pellentesque tellus. Etiam aliquam, sem sed posuere porta, nunc nibh lobortis ante, non rhoncus ipsum erat id tellus.

Sed in neque enim. Phasellus ante neque, egestas vel suscipit id, ultrices a lectus. Donec accumsan iaculis purus ut varius. Donec dolor nunc, malesuada eu semper vitae, efficitur ut arcu. Sed diam mi, auctor a elit blandit, pellentesque hendrerit leo. Donec scelerisque elit in placerat elementum. Sed velit erat, ullamcorper a diam in, iaculis pulvinar urna.

Aenean condimentum nisl in ultrices vehicula. Duis quis mi eget tellus cursus elementum ut et turpis. Praesent odio elit, condimentum vitae hendrerit eu, auctor nec odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam ac malesuada massa. Vestibulum ut ipsum faucibus, faucibus elit nec, viverra ipsum. Aenean gravida ex sodales dictum tristique. Praesent in orci sit amet libero molestie mattis sed non libero.

Curabitur vel neque velit. Vestibulum aliquam rhoncus mauris, a molestie tortor dapibus tempor. Morbi non nulla suscipit, ornare enim eu, ultrices purus. Mauris interdum, sem non mattis varius, risus orci aliquet massa, id convallis enim purus vel ex. Morbi non augue ac velit congue tristique ac viverra neque. Quisque hendrerit, lectus quis condimentum ultrices, metus leo dictum ligula, et porta elit mi at dolor. In hac habitasse platea dictumst. Vestibulum tempor odio odio, sit amet mattis leo euismod ac. Ut eget varius nisl. Fusce viverra lacus sed sagittis luctus. Donec id justo urna. Maecenas tellus velit, ullamcorper id porta a, finibus ut metus. Morbi vitae eros non metus condimentum vulputate aliquam ut justo. Quisque ac lacus lobortis, venenatis nunc vitae, hendrerit orci. Aliquam consectetur semper diam ut iaculis. Morbi a auctor ante.

Donec eu est eu sapien ultricies ullamcorper quis at quam. Sed sagittis, est ut luctus ornare, sem turpis dignissim orci, et viverra nibh ligula id ante. Ut ultrices libero dictum, sagittis justo quis, placerat erat. Pellentesque aliquet ligula ut felis tristique laoreet. Donec maximus lacus ut massa fringilla ultrices. Nam vulputate quis massa hendrerit efficitur. Ut metus metus, malesuada eget velit et, auctor vulputate nunc. Duis mattis auctor erat quis consectetur. Cras vitae tincidunt leo. Nullam tincidunt dignissim porttitor. Praesent venenatis sed massa ac lobortis. Nullam eu tellus non magna tincidunt pellentesque. Praesent sollicitudin dui tortor, ut porttitor tellus tristique ut. Sed euismod nisl eu urna vehicula, vel pharetra eros pharetra. Phasellus eleifend turpis at tortor elementum, a tincidunt turpis aliquam.

Quisque sagittis velit dapibus odio fermentum sollicitudin. Sed aliquet, eros eget imperdiet tristique, nisl urna porttitor mauris, sed accumsan nulla enim eu orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut nec feugiat enim, a pulvinar massa. Nunc vestibulum laoreet purus, in viverra augue bibendum eu. Fusce tempor luctus quam, id placerat urna. Suspendisse potenti. Praesent cursus at leo nec dignissim. Sed blandit lectus quis risus dapibus, sit amet vehicula purus tincidunt. Aliquam mollis tortor commodo accumsan cursus. Mauris dignissim eu ex at volutpat. Curabitur sagittis porta lorem, et luctus ipsum vulputate id. Nam venenatis, nulla in dictum accumsan, sapien neque condimentum quam, a tincidunt sem risus nec diam. Curabitur feugiat rutrum odio, nec lacinia enim cursus eget. Nam vel sem luctus, blandit nisl at, tempus eros. Vivamus a ante nibh.

Nunc egestas, nibh vel semper bibendum, nisl quam scelerisque quam, sit amet molestie massa risus sagittis dui. Nulla ante sem, ultricies vel ipsum id, bibendum porttitor sem. Praesent vel euismod felis. Praesent eleifend rutrum nibh. Quisque tempus sem vitae neque consectetur hendrerit. Aenean tristique non elit sit amet tempus. Duis faucibus augue vitae molestie ultrices. Aliquam ac nunc posuere, scelerisque lacus et, eleifend massa. Nulla accumsan, dui sit amet pellentesque faucibus, diam arcu sagittis ipsum, eu accumsan ligula lorem sit amet nisi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur ornare sagittis orci at lobortis. Curabitur quis accumsan est. Ut placerat neque non justo dictum iaculis. Nunc vehicula imperdiet feugiat. Fusce semper est at tortor viverra fermentum.

Curabitur vitae eros sed neque sollicitudin tristique in sit amet augue. Nunc vitae ligula quis orci sodales sollicitudin at vitae risus. Nulla aliquet leo nisi, id vestibulum massa tincidunt vehicula. Aliquam erat volutpat. Phasellus mattis ex nec neque laoreet varius. Phasellus interdum tincidunt dignissim. Nunc ex mi, consequat ut mollis a, sollicitudin eget lectus. Aliquam ac dictum diam.

Nunc pharetra accumsan nunc, eu mollis est viverra et. Morbi imperdiet nibh augue, a volutpat dolor hendrerit ut. Nullam eu tempus tellus, id imperdiet ipsum. Aliquam nec scelerisque libero, non tristique lorem. Fusce mattis augue lectus. Maecenas tristique purus nunc, at consequat urna sollicitudin sit amet. Vestibulum sit amet justo volutpat lacus convallis imperdiet. Sed condimentum facilisis massa, eget malesuada leo condimentum non. Etiam rutrum eros ac erat rhoncus, vel viverra lacus porttitor. Aenean eget justo ultricies, dapibus arcu in, iaculis velit. Cras rutrum, est at semper mattis, lorem mi accumsan orci, non molestie augue nisl vitae purus. Morbi varius purus risus, in consequat ipsum auctor eu. Morbi dictum diam turpis, vitae ullamcorper nunc ullamcorper ac.

Pellentesque eleifend non sem vitae placerat. Vivamus vitae felis lectus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris rutrum aliquam nulla, sed condimentum massa aliquam ac. Integer lacinia egestas erat, nec commodo tortor pretium quis. Quisque eget sagittis mi, eu elementum diam. In faucibus lobortis ullamcorper. Morbi sit amet tincidunt ante, id iaculis mi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Maecenas convallis non nisl in hendrerit. Nunc in malesuada massa. Morbi non elementum dolor. Ut ac ante consectetur, placerat ipsum sed, luctus purus. Vestibulum condimentum dui dolor, a fringilla felis semper vitae. Praesent in interdum est. Donec suscipit et felis et faucibus. Sed mattis, odio sed sollicitudin euismod, ex libero laoreet tellus, et malesuada ligula eros id orci.

Fusce fringilla diam in tempor interdum. Aliquam quis facilisis ipsum. Morbi vestibulum mattis sapien quis posuere. Curabitur vel neque tortor. In nunc erat, consectetur sed accumsan vitae, porttitor ut dolor. Pellentesque semper semper augue eu molestie. Sed et lectus in lacus pharetra commodo. Duis at ligula vitae neque tincidunt viverra. Donec tincidunt quam non maximus commodo. Maecenas consequat orci ac bibendum sodales. Nullam volutpat lectus odio, lobortis mattis enim luctus id. Nulla ac mollis nibh, non finibus quam. Aenean rutrum condimentum molestie. Integer scelerisque mi eu diam suscipit, sit amet sagittis leo dignissim. Nunc in nulla porta, volutpat nunc sed, volutpat libero.

Donec non sem elit. Duis vulputate neque justo, sed molestie augue auctor id. Vestibulum consectetur tempor rhoncus. Sed ultricies bibendum urna fermentum consectetur. Curabitur sodales ante magna, sed dignissim odio feugiat eget. Nullam rhoncus feugiat tellus volutpat molestie. Aenean imperdiet sed nunc et feugiat. Curabitur sed urna blandit, pulvinar metus at, volutpat tortor.

Etiam accumsan nisi sagittis mi vestibulum, sed dapibus nibh elementum. Cras vel turpis varius, molestie eros eget, tempor nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at velit lacinia, luctus dui vel, semper arcu. Etiam laoreet malesuada cursus. Morbi nec sem in justo sagittis iaculis. Sed consequat non lectus et condimentum. Cras vel tempor diam. Quisque malesuada porta est, a feugiat enim pharetra sit amet. Curabitur quam ex, euismod a eros interdum, efficitur bibendum tellus. Curabitur rutrum sagittis turpis.

Donec aliquet fermentum ligula at sodales. Suspendisse condimentum rutrum ligula sodales luctus. Pellentesque quam metus, consectetur ut mi sed, suscipit posuere lacus. Sed et ultrices sapien. Nulla eget nisl ligula. Cras hendrerit, lacus at posuere feugiat, purus ante sollicitudin nibh, non volutpat augue nibh quis turpis. Nunc bibendum mollis nisi a ornare. Sed euismod posuere quam id rutrum. Phasellus a consequat ipsum. Cras at ante id velit ultrices maximus. Cras sollicitudin elit ultrices auctor consequat. Mauris iaculis imperdiet ligula sed placerat. Vestibulum quis magna faucibus, mattis nulla condimentum, feugiat metus.

Integer nec velit ex. Phasellus pretium ante sit amet lacus facilisis, quis gravida neque feugiat. Proin feugiat imperdiet ligula, sit amet ultrices tellus iaculis vitae. Nulla congue, nibh eu condimentum maximus, mauris augue imperdiet velit, sed auctor est felis eget velit. Proin rutrum neque eros, vel posuere eros bibendum eget. Aliquam pharetra neque purus, in posuere nunc porttitor a. Duis sed feugiat lorem. Integer in lacus nisi. Fusce id dignissim dolor.

Fusce scelerisque, turpis et laoreet feugiat, erat mauris laoreet lectus, sit amet tincidunt dolor risus vitae nisl. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi ullamcorper elit non nisl rutrum, vel dapibus justo consequat. Nam maximus nisi ac sem ultrices, id dignissim eros venenatis. Pellentesque convallis dui nec mauris scelerisque, ac eleifend libero placerat. Maecenas mollis hendrerit neque, eu blandit erat condimentum sit amet. Morbi efficitur sit amet risus eget sollicitudin. Mauris dictum et leo at bibendum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus ultricies est a condimentum malesuada. Donec aliquet ex et nulla consequat viverra. Curabitur ultrices varius nisl, et hendrerit lorem porttitor et. In pulvinar sem accumsan, posuere nisi ac, ultrices eros.

Pellentesque non erat quis odio consequat tempor. Duis lacinia dolor ex, sed molestie lorem pretium eget. Etiam in leo eget ipsum tincidunt molestie. Donec eget facilisis metus, in laoreet libero. Etiam eget ante non ex luctus sollicitudin ut ac mi. Aenean sem diam, hendrerit vitae venenatis ut, tincidunt ac ligula. Nullam iaculis molestie mauris, nec euismod est accumsan et. Pellentesque viverra turpis velit, non venenatis urna luctus sed. Cras accumsan urna eget purus malesuada, et cursus nisl tincidunt. Donec consectetur imperdiet urna vel fermentum. Sed in tristique nunc. Ut nec orci vel tellus euismod venenatis tincidunt nec nisl. Morbi eget auctor velit. Nulla facilisi.

Maecenas posuere a dui consequat posuere. Cras finibus bibendum mi, sed interdum arcu suscipit a. Ut tincidunt quam vel condimentum sodales. Praesent et libero congue, consequat nulla quis, interdum orci. Aenean non velit ullamcorper, fermentum nulla at, consectetur turpis. Vestibulum pharetra mauris sit amet mattis ullamcorper. Donec ac ullamcorper leo. Morbi consectetur, nulla eget cursus porttitor, metus justo feugiat mi, non tincidunt lorem leo nec dolor. Phasellus malesuada ullamcorper lectus et condimentum. Donec dolor arcu, mollis et porta sed, dictum ac ante. Morbi at nulla quis nisl luctus viverra.

Sed vitae nisi sit amet augue accumsan pulvinar. Pellentesque eleifend orci in suscipit sollicitudin. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam auctor sapien a justo aliquam, eu ullamcorper dolor dictum. Fusce tristique orci ut risus tincidunt, et ornare elit accumsan. Mauris a consectetur lacus. Vestibulum pretium at nunc non iaculis. Nullam bibendum at urna sed blandit. Nulla facilisi. Cras rhoncus est a augue dapibus, rhoncus finibus elit vestibulum. Integer laoreet sodales arcu a sodales. Vestibulum urna lorem, efficitur id aliquet id, aliquet quis ligula. Nulla ac dolor justo. Vivamus id magna ut elit venenatis varius. Proin eu urna nisi. Morbi quis nulla vitae ipsum elementum posuere.

Vestibulum pretium accumsan ornare. Pellentesque placerat lectus ligula, sed egestas ante suscipit at. Donec eu eros quis odio ullamcorper dictum et non ante. Cras sapien elit, consequat vel leo ut, rutrum pretium neque. Duis tincidunt velit libero, eget tristique dolor fringilla blandit. Pellentesque venenatis diam sed tortor suscipit sagittis. Etiam aliquet quam tortor, ultrices dictum dui convallis vitae. Vestibulum dolor massa, gravida vitae dolor ac, cursus egestas neque. Donec sed tellus mattis, convallis elit a, tempus nisi.

Phasellus aliquam nibh sed dictum lobortis. In pulvinar diam sit amet arcu feugiat eleifend. Vestibulum eget auctor purus, id tristique ipsum. Donec luctus ex at ante rutrum, vel posuere libero dignissim. Cras accumsan tincidunt vestibulum. Curabitur quis efficitur arcu. Aenean quam dolor, volutpat in eros ut, accumsan sollicitudin nulla. Vestibulum et fringilla nisi. Mauris eget est id eros imperdiet egestas. Donec rhoncus massa nec erat mollis, nec feugiat magna maximus. Maecenas semper rhoncus eros, ut interdum orci aliquet sed. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras at ante sit amet mi varius pellentesque non eget urna.

Fusce sed vestibulum ex, at tristique diam. Donec lobortis nisi id nibh dapibus, vel dapibus dolor tempor. Aliquam ultricies urna erat, eget lobortis ante efficitur et. Aenean mi felis, interdum in velit a, tempus elementum risus. Praesent auctor egestas pharetra. Praesent gravida mattis ornare. Aenean pellentesque, tellus id bibendum auctor, neque felis molestie ex, ac lacinia ligula felis eu nulla.

Maecenas nisi velit, iaculis nec cursus eu, semper posuere neque. Morbi eu facilisis ipsum, non auctor augue. Sed gravida augue est, et auctor massa feugiat quis. Mauris at tristique felis. Fusce luctus iaculis vehicula. Nulla tristique purus velit, quis tristique arcu condimentum ut. Vivamus et purus facilisis, dapibus dolor vel, viverra nunc.

Cras ac eros neque. Nunc vulputate urna a eros sagittis, eu pellentesque diam sollicitudin. Nunc nunc neque, posuere vitae volutpat non, congue at velit. Sed quis sapien iaculis, consectetur nisl et, lobortis mauris. Vivamus ac accumsan felis. Maecenas non magna condimentum, faucibus lorem vel, consectetur est. Integer volutpat mi lorem, in iaculis."""

split_time = 0
regex_time = 0
for i in range(500):
    time1 = time.time()
    lipsum.split()
    split_time += time.time() - time1
    time2 = time.time()
    re.findall(r'\w+', lipsum)
    regex_time += time.time() - time2

print(f"Total Time for Split = {split_time}")
print(f"Average Time for Split = {split_time / 500}")
print(f"Total Time for Regex = {regex_time}")
print(f"Average Time for Regex = {regex_time / 500}")
